// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1BOVxhCFTXQHz_2yWdHAVBbDLh_NmUVs',
    appId: '1:106985657225:web:67c759ce62aaaa3c5a4758',
    messagingSenderId: '106985657225',
    projectId: 'contact-app-2bd5f',
    authDomain: 'contact-app-2bd5f.firebaseapp.com',
    storageBucket: 'contact-app-2bd5f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPepgEXVkAqdVZFAtRSjTR4Z3QbUCbCxM',
    appId: '1:106985657225:android:1ce1aa72cab081625a4758',
    messagingSenderId: '106985657225',
    projectId: 'contact-app-2bd5f',
    storageBucket: 'contact-app-2bd5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA61hkDPTdNylQo0-90Lzlc_DXlBBU1w4o',
    appId: '1:106985657225:ios:48acee1f549d18405a4758',
    messagingSenderId: '106985657225',
    projectId: 'contact-app-2bd5f',
    storageBucket: 'contact-app-2bd5f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA61hkDPTdNylQo0-90Lzlc_DXlBBU1w4o',
    appId: '1:106985657225:ios:48acee1f549d18405a4758',
    messagingSenderId: '106985657225',
    projectId: 'contact-app-2bd5f',
    storageBucket: 'contact-app-2bd5f.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1BOVxhCFTXQHz_2yWdHAVBbDLh_NmUVs',
    appId: '1:106985657225:web:2502113aa34107325a4758',
    messagingSenderId: '106985657225',
    projectId: 'contact-app-2bd5f',
    authDomain: 'contact-app-2bd5f.firebaseapp.com',
    storageBucket: 'contact-app-2bd5f.firebasestorage.app',
  );
}
